### ISSUE TITLE
Permission Denied Error during execution of code 

### ISSUE THREAD

**Issue by jjsr** [FactoDeepLearning/VerticalAttentionOCR#10]
Hi I am getting this error while executing the code on Centos7.6, any idea sir what is causing this error ?? Thanking in advance sir 

` File "main_pg_va.py", line 228, in <module>
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/user/handwritten-text-recognition/data/yes/envs/torch/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/user/handwritten-text-recognition/data/yes/envs/torch/lib/python3.8/site-packages/tensorboard/summary/writer/event_file_writer.py", line 238, in run
    self._record_writer.write(data)
  File "/home/user/handwritten-text-recognition/data/yes/envs/torch/lib/python3.8/site-packages/tensorboard/summary/writer/record_writer.py", line 40, in write
    train_and_test(0, params)
  File "main_pg_va.py", line 52, in train_and_test
    self._writer.write(header + header_crc + data + footer_crc)
  File "/home/user/handwritten-text-recognition/data/yes/envs/torch/lib/python3.8/site-packages/tensorboard/compat/tensorflow_stub/io/gfile.py", line 531, in write
    model.train()
  File "/home/user/VerticalAttentionOCR/OCR/document_OCR/v_attention/../../../basic/generic_training_manager.py", line 521, in train
    self.fs.append(self.filename, file_content, self.binary_mode)
  File "/home/user/handwritten-text-recognition/data/yes/envs/torch/lib/python3.8/site-packages/tensorboard/compat/tensorflow_stub/io/gfile.py", line 154, in append
    self._write(filename, file_content, "ab" if binary_mode else "a")
  File "/home/user/handwritten-text-recognition/data/yes/envs/torch/lib/python3.8/site-packages/tensorboard/compat/tensorflow_stub/io/gfile.py", line 158, in _write
    with io.open(filename, mode, encoding=encoding) as f:
PermissionError: [Errno 13] Permission denied: b'/home/user/VerticalAttentionOCR/results/page/results/events.out.tfevents.1645012223.gpu006.iinst.ac.in.40848.0'
    self.save_model(epoch=num_epoch, name="last")
  File "/home/user/VerticalAttentionOCR/OCR/document_OCR/v_attention/../../../basic/generic_training_manager.py", line 276, in save_model
    for filename in os.listdir(self.paths["checkpoints"]):
PermissionError: [Errno 13] Permission denied: '/home/user/VerticalAttentionOCR/results/page/checkpoints'`

**Comment by jjsr** [comment]
I was getting this error in sections where it removes the earlier snaps of saved model. I have commented those line as a way around and now it may work fine . Closing the issue
